name: EPG-XML Generator

on:
  schedule:
    - cron: '0 0 * * 3'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run grab -- --site=toonamiaftermath.com
    - name: config
      run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
    - name: git add
      run: |
          git add -f guide.xml
          ls -la
    - name: commit & push
      run: |
          git commit -m "xml is updated"
          git push
    
